#!/bin/bash
COLUMNS=$(tput cols)
if [ $# = 1 ]
	then
		VAR=$(curl -s https://api.twitch.tv/kraken/streams/$1?client_id=8tjnx272gikhemkvfodelhap9qpdli)
		STREAM_OFF=$(echo $VAR | cut -d ',' -f 1 | cut -d ':' -f 2)
		GAME=$(echo $VAR | cut -d '"' -f8 | sed 's/\\u0026/\&/g')
		VIEWERS=$(echo $VAR | cut -d ',' -f 3 | cut -d ':' -f 2)
		DESC=$(echo $VAR | cut -d '"' -f54 | sed 's/\\u0026/\&/g')
		FOLLOWS=$(echo $VAR | cut -d '"' -f119 | sed 's/://g' | sed 's/,//g')
		VIEWS=$(echo $VAR | cut -d '"' -f117 | sed 's/://g' | sed 's/,//g')
		URL=$(echo $VAR | cut -d '"' -f 114)
		if [ $STREAM_OFF = null ]
			then
				echo "Ce streamer n'est pas en stream actuellement!"| fmt -c -w $COLUMNS
			else
				echo "$1 est en stream et joue a $GAME!" | fmt -c -w $COLUMNS
				echo "----" | fmt -c -w $COLUMNS
				echo "\"$DESC\"" | fmt -c -w $COLUMNS
				echo "----" | fmt -c -w $COLUMNS
				echo "Il a actuellement $VIEWERS viewers" | fmt -c -w $COLUMNS
				echo "----" | fmt -c -w $COLUMNS
				echo "Il possede $FOLLOWS followers et $VIEWS vues sur sa chaine" | fmt -c -w $COLUMNS
				echo "----" | fmt -c -w $COLUMNS
				echo "URL du stream: $URL" | fmt -c -w $COLUMNS
			fi
	else
		echo "Choisissez un streamer valide"
	fi
